### ISSUE TITLE
Add Static Files Directory

### ISSUE THREAD

**Issue by liljoker919** [liljoker919/clnickerson#5]
Currently, our Django project is missing a static files directory, which has caused a warning during the `makemigrations` process:

```
WARNINGS:
?: (staticfiles.W004) The directory '/home/ubuntu/clnickerson/website/static' in the STATICFILES_DIRS setting does not exist.
```

### Tasks:

- [ ] Create a `static` directory inside the `website` directory.
- [ ] Ensure the `STATICFILES_DIRS` setting in `settings.py` is correctly pointing to the new `static` directory.
- [ ] Test to confirm that the warning is resolved during the `makemigrations` and `collectstatic` processes.
- [ ] Update any relevant documentation to include information about the static files directory.

### Additional Context:

Static files (like CSS, JavaScript, and images) are essential for the frontend of our Django application. Properly setting up the static files directory ensures that these assets are correctly handled during development and deployment.

---

You can copy and paste this into a new issue on GitHub to help track and resolve the missing static files directory in your project.
